#!/bin/bash

echo '################################################################################'
echo '# The following output is used to setup aliases to containerized pca-assessment commands'
echo '# To apply these changes under bash use a command similar to:'
echo '# eval "$(docker run pca-assessment)"'
echo '#'
echo '# Environment variables:'
echo '# PCA_CON_IMAGE, defaults to "pca-assessment" if not set'
echo '# '
echo '################################################################################'
echo

cd /usr/local/bin

# create output that can be evaled to create aliases for pca-assessment commands
for f in pca-*
do
  echo alias $f=\"docker run -it --rm --volume \\\`pwd\\\`:/home/pca \\\"\\\${PCA_CON_IMAGE:-pca-assessment}\\\" $f\"
done

# create an alias to start bash in the container
echo alias pca-assessment-bash=\"docker run -it --rm --volume \\\`pwd\\\`:/home/pca \\\"\\\${PCA_CON_IMAGE:-pca-assessment}\\\" /bin/bash\"