---
name: release

on:
  release:
    types: [prereleased, released]

env:
  IMAGE_NAME: cisagov/gophish-tools
  DOCKER_PW: ${{ secrets.DOCKER_PW }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Determine image version
        id: get_ver
        run: |
          echo "##[set-output name=version;]$(./bump_version.sh project show)"
      - name: Build Docker image
        run: |
          docker build \
            --tag "$IMAGE_NAME" \
            --build-arg GIT_COMMIT=$(git log -1 --format=%H) \
            --build-arg GIT_REMOTE=$(git remote get-url origin) \
            --build-arg VERSION=${{ steps.get_ver.outputs.version }} \
            .
      - name: Tag Docker image
        run: |
          IFS='.' read -r -a version_array \
            <<< "${{ steps.get_ver.outputs.version }}"
          docker login --username "$DOCKER_USER" --password "$DOCKER_PW"
          docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
          docker tag "$IMAGE_NAME" \
            "${IMAGE_NAME}:${{ steps.get_ver.outputs.version }}"
          docker tag "$IMAGE_NAME" \
            "${IMAGE_NAME}:${version_array[0]}.${version_array[1]}"
          docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version_array[0]}"
      - name: Publish image to Docker Hub
        run: |
          IFS='.' read -r -a version_array \
            <<< "${{ steps.get_ver.outputs.version }}"
          docker push "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:${{ steps.get_ver.outputs.version }}"
          docker push "${IMAGE_NAME}:${version_array[0]}.${version_array[1]}"
          docker push "${IMAGE_NAME}:${version_array[0]}"
      - name: Publish README.md to Docker Hub
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PW }}
          DOCKERHUB_REPOSITORY: ${{ env.IMAGE_NAME }}
